name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main
    paths:
      - 'src/ci-/**'
env:
  REG_NAME: acrinfobi22210.azurecr.io # Nom du registy
  IMAGE_NAME: be-eo # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REG_NAME }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -f src/backend/Dockerfile \
            -t ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            src/backend

      - name: Push Docker image
        run: |
          docker push ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
